export const STOP_WORDS: readonly string[] = [
  // Irrelevant niches
  'казино',
  'wordpress',
  'реферат',
  'диплом',
  'курсова',
  'есе',
  'adult',
  'dating',
  'betting',
  'crypto',
  'нфт',
  'nft',
  // Full-time / permanent employment markers — we want one-off gigs only
  'full-time',
  'full time',
  'fulltime',
  'фуллтайм',
  'в штат',
  'постійна робота',
  'постоянная работа',
  'довгостроков',
  'долгосрочн',
  'looking for someone to join',
  'join our team permanently',
  'permanent position',
  'permanent role',
];
